name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: Build
      run: "npm install && npm run build"

    - name: Create Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{github.ref_name}}
          files: |
            dist/csm10495-plugin.js